version: '3.3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: 'digital_menu'
      POSTGRES_USER: 'valentin'
      POSTGRES_PASSWORD: 'valentin'
    ports:
      - '5432:5432'
    volumes:
      - my-db:/var/lib/postgresql/data
volumes:
  my-db: